/*
 * TLS protocol versions
 */


TLS_PROTO(SSL3_VERSION,		"SSLv3",	SSL_OP_NO_SSLv3)
TLS_PROTO(TLS1_VERSION,		"TLSv1.0",	SSL_OP_NO_TLSv1)
TLS_PROTO(TLS1_1_VERSION,	"TLSv1.1",	SSL_OP_NO_TLSv1_1)
TLS_PROTO(TLS1_2_VERSION,	"TLSv1.2",	SSL_OP_NO_TLSv1_2)
#if defined(TLS1_3_VERSION) || OPENSSL_VERSION_NUMBER >= 0x10101000L
TLS_PROTO(TLS1_3_VERSION,	"TLSv1.3",	SSL_OP_NO_TLSv1_3)
#endif
#undef TLS_PROTO
